<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\ParkingSlot;

class ParkingSlotSeederp3p1 extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $parkingSlots = [
            // Columna 1
            [
                'name' => '1-1',
                'slotType' => 'normal',
                'assigned' => true,
                'slotStatus' => 'open',
                'assignedPlate' => '1234ABC',
                'x1' => 100,
                'y1' => 100,
                'x2' => 300,
                'y2' => 200,
                'floor_id' => 5,
            ],
            [
                'name' => '1-2',
                'slotType' => 'normal',
                'assigned' => true,
                'slotStatus' => 'open',
                'assignedPlate' => '5678DEF',
                'x1' => 100,
                'y1' => 200,
                'x2' => 300,
                'y2' => 300,
                'floor_id' => 5,
            ],
            [
                'name' => '1-3',
                'slotType' => 'normal',
                'assigned' => true,
                'slotStatus' => 'open',
                'assignedPlate' => '9012GHI',
                'x1' => 100,
                'y1' => 300,
                'x2' => 300,
                'y2' => 400,
                'floor_id' => 5,
            ],
            [
                'name' => '1-4',
                'slotType' => 'normal',
                'assigned' => true,
                'slotStatus' => 'open',
                'assignedPlate' => '3456JKL',
                'x1' => 100,
                'y1' => 400,
                'x2' => 300,
                'y2' => 500,
                'floor_id' => 5,
            ],
            [
                'name' => '1-5',
                'slotType' => 'normal',
                'assigned' => true,
                'slotStatus' => 'open',
                'assignedPlate' => '7890MNO',
                'x1' => 100,
                'y1' => 500,
                'x2' => 300,
                'y2' => 600,
                'floor_id' => 5,
            ],
            
            // Columna 2
            [
                'name' => '2-1',
                'slotType' => 'normal',
                'assigned' => false,
                'slotStatus' => 'closed',
                'assignedPlate' => null,
                'x1' => 300,
                'y1' => 100,
                'x2' => 500,
                'y2' => 200,
                'floor_id' => 5,
            ],
            [
                'name' => '2-2',
                'slotType' => 'normal',
                'assigned' => false,
                'slotStatus' => 'closed',
                'assignedPlate' => null,
                'x1' => 300,
                'y1' => 200,
                'x2' => 500,
                'y2' => 300,
                'floor_id' => 5,
            ],
            [
                'name' => '2-3',
                'slotType' => 'normal',
                'assigned' => false,
                'slotStatus' => 'closed',
                'assignedPlate' => null,
                'x1' => 300,
                'y1' => 300,
                'x2' => 500,
                'y2' => 400,
                'floor_id' => 5,
            ],
            [
                'name' => '2-4',
                'slotType' => 'normal',
                'assigned' => false,
                'slotStatus' => 'closed',
                'assignedPlate' => null,
                'x1' => 300,
                'y1' => 400,
                'x2' => 500,
                'y2' => 500,
                'floor_id' => 5,
            ],
            [
                'name' => '2-5',
                'slotType' => 'normal',
                'assigned' => false,
                'slotStatus' => 'closed',
                'assignedPlate' => null,
                'x1' => 300,
                'y1' => 500,
                'x2' => 500,
                'y2' => 600,
                'floor_id' => 5,
            ],

            // Columna 3
            [
                'name' => '3-1',
                'slotType' => 'normal',
                'assigned' => true,
                'slotStatus' => 'open',
                'assignedPlate' => '2345PQR',
                'x1' => 650,
                'y1' => 100,
                'x2' => 850,
                'y2' => 200,
                'floor_id' => 5,
            ],
            [
                'name' => '3-2',
                'slotType' => 'normal',
                'assigned' => true,
                'slotStatus' => 'open',
                'assignedPlate' => '6789STU',
                'x1' => 650,
                'y1' => 200,
                'x2' => 850,
                'y2' => 300,
                'floor_id' => 5,
            ],
            [
                'name' => '3-3',
                'slotType' => 'normal',
                'assigned' => true,
                'slotStatus' => 'open',
                'assignedPlate' => '1234VWX',
                'x1' => 650,
                'y1' => 300,
                'x2' => 850,
                'y2' => 400,
                'floor_id' => 5,
            ],
            [
                'name' => '3-4',
                'slotType' => 'normal',
                'assigned' => true,
                'slotStatus' => 'open',
                'assignedPlate' => '5678YZA',
                'x1' => 650,
                'y1' => 400,
                'x2' => 850,
                'y2' => 500,
                'floor_id' => 5,
            ],
            [
                'name' => '3-5',
                'slotType' => 'normal',
                'assigned' => true,
                'slotStatus' => 'open',
                'assignedPlate' => '9101BCD',
                'x1' => 650,
                'y1' => 500,
                'x2' => 850,
                'y2' => 600,
                'floor_id' => 5,
            ],

            // Columna 4
            [
                'name' => '4-1',
                'slotType' => 'normal',
                'assigned' => false,
                'slotStatus' => 'closed',
                'assignedPlate' => null,
                'x1' => 850,
                'y1' => 100,
                'x2' => 1050,
                'y2' => 200,
                'floor_id' => 5,
            ],
            [
                'name' => '4-2',
                'slotType' => 'normal',
                'assigned' => false,
                'slotStatus' => 'closed',
                'assignedPlate' => null,
                'x1' => 850,
                'y1' => 200,
                'x2' => 1050,
                'y2' => 300,
                'floor_id' => 5,
            ],
            [
                'name' => '4-3',
                'slotType' => 'normal',
                'assigned' => false,
                'slotStatus' => 'closed',
                'assignedPlate' => null,
                'x1' => 850,
                'y1' => 300,
                'x2' => 1050,
                'y2' => 400,
                'floor_id' => 5,
            ],
            [
                'name' => '4-4',
                'slotType' => 'normal',
                'assigned' => false,
                'slotStatus' => 'closed',
                'assignedPlate' => null,
                'x1' => 850,
                'y1' => 400,
                'x2' => 1050,
                'y2' => 500,
                'floor_id' => 5,
            ],
            [
                'name' => '4-5',
                'slotType' => 'normal',
                'assigned' => false,
                'slotStatus' => 'closed',
                'assignedPlate' => null,
                'x1' => 850,
                'y1' => 500,
                'x2' => 1050,
                'y2' => 600,
                'floor_id' => 5,
            ],

            // Columna 5
            [
                'name' => '5-1',
                'slotType' => 'motorbike',
                'assigned' => true,
                'slotStatus' => 'open',
                'assignedPlate' => '1122EFG',
                'x1' => 1250,
                'y1' => 100,
                'x2' => 1450, 
                'y2' => 200,
                'floor_id' => 5,
            ],
            [
                'name' => '5-2',
                'slotType' => 'motorbike',
                'assigned' => true,
                'slotStatus' => 'open',
                'assignedPlate' => '2233HIJ',
                'x1' => 1250,
                'y1' => 150,
                'x2' => 1450, 
                'y2' => 250,
                'floor_id' => 5,
            ]
        ];

        foreach ($parkingSlots as $slot) {
            ParkingSlot::create($slot);
        }
    }
}
